name: Check links

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:

  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Markup Link Checker (mlc)
        uses: becheran/mlc@7ec24825cefe0c9c8c6bac48430e1f69e3ec356e # v1.2.0
        # from https://github.com/becheran/mlc
