name: Prek auto-update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # Every 1st of the month at 00:00 UTC

permissions: write-all

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: "true"
          cache-suffix: "3.12"
          cache-dependency-glob: "pyproject.toml"
      - name: prek install autoupdate
        run: |
          uv pip install prek --system
          prek auto-update
      - name: Commit and push changes
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          branch: update-prek-hooks
          title: 'Update prek hooks'
          commit-message: 'Update prek hooks'
          body: Update versions of prek hooks to latest versions.
