name: Prek auto-update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # Every 1st of the month at 00:00 UTC

permissions: write-all

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: "true"
          cache-suffix: "3.12"
          cache-dependency-glob: "pyproject.toml"
      - name: prek install autoupdate
        run: |
          uv pip install prek --system
          prek auto-update
      - name: Commit and push changes
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          branch: update-prek-hooks
          title: 'Update prek hooks'
          commit-message: 'Update prek hooks'
          body: Update versions of prek hooks to latest versions.
