name: Prek auto-update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # Every 1st of the month at 00:00 UTC

permissions: write-all

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: "true"
          cache-suffix: "3.12"
          cache-dependency-glob: "pyproject.toml"
      - name: prek install autoupdate
        run: |
          uv pip install prek --system
          prek auto-update
      - name: Commit and push changes
        uses: peter-evans/create-pull-request@v8
        with:
          branch: update-prek-hooks
          title: 'Update prek hooks'
          commit-message: 'Update prek hooks'
          body: Update versions of prek hooks to latest versions.
